apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-petstore
  annotations:
    github.com/project-slug: marissass/swagger-petstore
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: marissass
  system: pets
  dependsOn:
    - resource:default/pets-db
  providesApis:
    - swagger-petstore-api
    - Traffic-kafka-v1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: swagger-petstore-api
  description: The Petstore - OpenAPI 3.0
  tags:
    - store
    - rest
    - pet
  links:
    - url: https://github.com/marissass/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/marissass/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: marissass
  system: pets
  definition:
    $text: https://github.com/marissass/swagger-petstore/blob/master/src/main/resources/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Traffic-kafka-v1
  description: The Traffic events - AsyncAPI 1.0
  tags:
    - traffic
    - rest
  links:
    - url: https://github.com/asyncapi/spec
      title: GitHub Repo
      icon: github
    - url: https://github.com/asyncapi/spec/blob/master/examples/streetlights-kafka-asyncapi.yml
      title: API Spec
      icon: code
spec:
  type: asyncapi
  lifecycle: production
  owner: marissass
  system: pets
  definition:
    $text: https://github.com/marissass/swagger-petstore/blob/master/AsyncAPI/TrafficLights.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pets-db
  description: Stores pets details
spec:
  type: database
  owner: marissass
  system: pets