apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-petstore
  annotations:
    github.com/project-slug: marissass/swagger-petstore
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: marissass
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - swagger-petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: swagger-petstore-api
  description: The petstore swagger api example
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: dev
  owner: marissass
  definition:
    $text: ./petstore.oas.yaml