apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-petstore
  annotations:
    github.com/project-slug: marissass/swagger-petstore
    backstage.io/techdocs-ref: dir: .
spec:
  type: other
  lifecycle: unknown
  owner: marissass
