apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-petstore
  annotations:
    github.com/project-slug: marissass/swagger-petstore
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: marissass
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - swagger-petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: swagger-petstore-api
  description: The petstore swagger api example
spec:
  type: openapi
  lifecycle: production
  owner: marissass
  definition:
    $text: https://github.com/marissass/swagger-petstore/blob/master/src/main/resources/openapi.yaml
